### ISSUE TITLE
chex and jax versison conflict

### ISSUE THREAD

**Issue by luli-git** [som-shahlab/ehrshot-benchmark#19]
Hi there, 

I was trying to run the run_all.sh file following the instructions. However, when I run the following command: 

```
pip install femr-cuda==0.0.20 dm-haiku==0.0.9 optax==0.1.4
pip install --upgrade "jax[cuda]==0.4.8" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

```
It gives me the following error: 

> Looking in links: https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
> Collecting jax==0.4.8 (from jax[cuda]==0.4.8)
>   Using cached jax-0.4.8-py3-none-any.whl
> Requirement already satisfied: ml-dtypes>=0.0.3 in /home/luli/miniconda3/envs/EHRSHOT_ENV/lib/python3.10/site-packages (from jax==0.4.8->jax[cuda]==0.4.8) (0.4.0)
> Requirement already satisfied: numpy>=1.21 in /home/luli/miniconda3/envs/EHRSHOT_ENV/lib/python3.10/site-packages (from jax==0.4.8->jax[cuda]==0.4.8) (1.26.4)
> Requirement already satisfied: opt-einsum in /home/luli/miniconda3/envs/EHRSHOT_ENV/lib/python3.10/site-packages (from jax==0.4.8->jax[cuda]==0.4.8) (3.3.0)
> Requirement already satisfied: scipy>=1.7 in /home/luli/miniconda3/envs/EHRSHOT_ENV/lib/python3.10/site-packages (from jax==0.4.8->jax[cuda]==0.4.8) (1.10.1)
> Collecting jaxlib==0.4.7+cuda11.cudnn86 (from jax[cuda]==0.4.8)
>   Using cached https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.4.7%2Bcuda11.cudnn86-cp310-cp310-manylinux2014_x86_64.whl (152.0 MB)
> Installing collected packages: jaxlib, jax
>   Attempting uninstall: jaxlib
>     Found existing installation: jaxlib 0.4.34
>     Uninstalling jaxlib-0.4.34:
>       Successfully uninstalled jaxlib-0.4.34
>   Attempting uninstall: jax
>     Found existing installation: jax 0.4.34
>     Uninstalling jax-0.4.34:
>       Successfully uninstalled jax-0.4.34
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> chex 0.1.86 requires jax>=0.4.16, but you have jax 0.4.8 which is incompatible.
> flax 0.9.0 requires jax>=0.4.27, but you have jax 0.4.8 which is incompatible.
> orbax-checkpoint 0.7.0 requires jax>=0.4.34, but you have jax 0.4.8 which is incompatible.
> Successfully installed jax-0.4.8 jaxlib-0.4.7+cuda11.cudnn86
> 

Even with this error, when I print the versions for jax and chex, they seem correct:
>>> import jax
>>> jax.__version__
'0.4.8'
>>> import chex
>>> chex.__version__
'0.1.86'
>>> 

However, when I run step 5 from run_all.sh, I run into the following error: 

> 
> 2024-10-14 23:36:56,327 [MainThread  ] [INFO ]  Loaded
> When mapping codes, dropped 4744 out of 39811
> 2024-10-14 23:37:00,942 [MainThread  ] [INFO ]  Number of train patients 183
> 2024-10-14 23:37:01.413 | SUCCESS  | __main__:<module>:57 - Finish | Create CLMBR batches @ ../../EHRSHOT_ASSETS/features/clmbr_batches
> 2024-10-14 23:37:01.413 | INFO     | __main__:<module>:69 - Start | Create CLMBR representations @ ../../EHRSHOT_ASSETS/features/clmbr_features.pkl
> 2024-10-14 23:37:01.413 | CRITICAL | __main__:<module>:70 - Command run:
> clmbr_compute_representations ../../EHRSHOT_ASSETS/features/clmbr_features.pkl --data_path ../../EHRSHOT_ASSETS/femr/extract --batches_path ../../EHRSHOT_ASSETS/features/clmbr_batches --model_dir ../../EHRSHOT_ASSETS/models/clmbr/clmbr_model
> Traceback (most recent call last):
>   File "/home/luli/miniconda3/envs/EHRSHOT_ENV/bin/clmbr_compute_representations", line 5, in <module>
>     from femr.models.scripts import compute_representations
>   File "/home/luli/miniconda3/envs/EHRSHOT_ENV/lib/python3.10/site-packages/femr/models/scripts.py", line 12, in <module>
>     import haiku as hk
>   File "/home/luli/miniconda3/envs/EHRSHOT_ENV/lib/python3.10/site-packages/haiku/__init__.py", line 20, in <module>
>     from haiku import experimental
>   File "/home/luli/miniconda3/envs/EHRSHOT_ENV/lib/python3.10/site-packages/haiku/experimental/__init__.py", line 34, in <module>
>     from haiku._src.dot import abstract_to_dot
>   File "/home/luli/miniconda3/envs/EHRSHOT_ENV/lib/python3.10/site-packages/haiku/_src/dot.py", line 29, in <module>
>     from jax.extend import linear_util as lu
> ModuleNotFoundError: No module named 'jax.extend'
> Traceback (most recent call last):
>   File "/home/luli/ehrshot-benchmark/ehrshot/bash_scripts/../5_generate_clmbr_features.py", line 71, in <module>
>     assert 0 == os.system(command)
> AssertionError
> 

Is there a specific chex version that I need to install? Please kindly help. Thank you!

**Comment by luli-git** [comment]
I was able to fix this issue by installing CUDA 11.8 and cuDNN 8.7.0.
